Arjun add budget script
Brainlabs-Digital/Google-Ads-Scripts pull request #19
Opened 2020-02-12 14:57 UTC by arjun-raja

2020-02-21 16:18 UTC, gideon-brainlabs requested changes
Looks great! I've suggested some changes.

2020-02-21 16:18 UTC, gideon-brainlabs commented on Managing/budget_manager.js
> +var CONFIG_DATA_ROW = 3;
```suggestion
var CONFIG_FIRST_DATA_ROW = 3;
```

2020-02-21 16:18 UTC, gideon-brainlabs commented on Managing/budget_manager.js
> +    var configSheet = spreadsheet.getSheetByName("Configuation");
```suggestion
    var configSheet = spreadsheet.getSheetByName("Configuration");
```

2020-02-21 16:18 UTC, gideon-brainlabs commented on Managing/budget_manager.js
> +    var dashboardSheet = spreadsheet.getSheetByName("Dashboard");
```suggestion
    var dashboardSheet = spreadsheet.getSheetByName("Budget Dashboard");
```

2020-02-21 16:18 UTC, gideon-brainlabs commented on Managing/budget_manager.js
> +    var dashboardSheet = spreadsheet.getSheetByName("Dashboard");
```suggestion
    var dashboardSheet = spreadsheet.getSheetByName("Budget Dashboard");
```

2020-02-21 16:18 UTC, gideon-brainlabs commented on Managing/budget_manager.js
> +    var allData = configSheet.getRange(CONFIG_DATA_ROW, 1, configSheet.getLastRow() - (CONFIG_HEADER_ROW + 1), configSheet.getLastColumn()).getValues();
```suggestion
    var allData = configSheet.getRange(CONFIG_DATA_FIRST_ROW, 1, configSheet.getLastRow() - (CONFIG_HEADER_ROW + 1), configSheet.getLastColumn()).getValues();
```

2020-02-21 16:18 UTC, gideon-brainlabs commented on Managing/budget_manager.js
> +    Logger.log('Checking spreadsheet: ' + SPREADSHEET_URL + ' is valid.');
```suggestion
    Logger.log('Checking spreadsheet: ' + spreadsheetUrl + ' is valid.');
```

2020-02-21 16:18 UTC, gideon-brainlabs commented on Managing/budget_manager.js
> +        throw ("Problem with " + SPREADSHEET_URL +
```suggestion
        throw ("Problem with " + spreadsheetUrl +
```

2020-02-21 16:18 UTC, gideon-brainlabs commented on Managing/budget_manager.js
> +    }
Very nice!!

2020-02-21 16:18 UTC, gideon-brainlabs commented on Managing/budget_manager.js
> +    var whereStatement = "WHERE BudgetStatus != REMOVED ";
Does it need to be `"WHERE BudgetStatus != 'REMOVED'"`, with REMOVED as a string?

2020-02-21 16:18 UTC, gideon-brainlabs commented on Managing/budget_manager.js
> +        whereStatement += "AND AssociatedCampaignStatus = ENABLED ";
Here too, does it need to be `'ENABLED'`?

2020-02-21 16:18 UTC, gideon-brainlabs commented on Managing/budget_manager.js
> +            break;;
```suggestion
            break;
```

2020-02-21 16:18 UTC, gideon-brainlabs commented on Managing/budget_manager.js
> +            }).join(',') + " FROM BUDGET_PERFORMANCE_REPORT " + queries[i]
I don't think we need the `map` here, could use:
```
"SELECT" + fields.join(',') + " FROM BUDGET_PERFORMANCE_REPORT " + queries[i]
```

2020-02-21 16:18 UTC, gideon-brainlabs commented on Managing/budget_manager.js
> +    Logger.log("Success");
Do we want to also log, before these, `Logger.log("updating budgets");`?

2020-02-21 16:18 UTC, gideon-brainlabs commented on Managing/budget_manager.js
> +
Do we still need this section?

2020-02-21 16:18 UTC, gideon-brainlabs commented on Managing/budget_manager.js
> +        writeRowsOntoSheet(dasboardSheet, dashboardRows);
```suggestion
        writeRowsOntoSheet(dashboardSheet, dashboardRows);
```

2020-02-24 11:12 UTC, arjun-raja reviewed
thanks for looking through!

2020-02-24 11:12 UTC, arjun-raja commented on Managing/budget_manager.js
> +
no - will remove

2020-02-24 11:12 UTC, arjun-raja commented on Managing/budget_manager.js
> +    Logger.log("Success");
👍

2020-02-24 11:12 UTC, arjun-raja commented on Managing/budget_manager.js
> +    var whereStatement = "WHERE BudgetStatus != REMOVED ";
yup it does!

2020-02-24 11:12 UTC, arjun-raja commented on Managing/budget_manager.js
> +            break;;
;__;

2020-02-24 11:12 UTC, arjun-raja commented on Managing/budget_manager.js
> +            }).join(',') + " FROM BUDGET_PERFORMANCE_REPORT " + queries[i]
`fields.join(',')` won't work, as we want the fields to still be in an array. `Array.from()` would be neater, but haven't seen the option to use modern Javascript in Google Ads Scripts yet.

2020-02-24 12:06 UTC, gideon-brainlabs approved these changes

2020-02-24 13:29 UTC, merged